### ISSUE TITLE
optional questions rewrite other values?

### ISSUE THREAD

**Issue by makiren** [usame-algan/cf7-zoom-webinar-registration#1]
I've found the value of _first_name_ is somehow rewritten or changed to the same value as _last_name._  Still checking and am after the source of error.

**Comment by usame-algan** [comment]
Hi @makiren,

can you post a list of your field names in contact form 7 and zoom fields that are displayed under the Zoom panel so I can try to recreate the bug. Thanks!

**Comment by makiren** [comment]
@usame-algan 
Fields were all required and name are as shown in the picture, last_name, first_name, and email. I bet it should be correct and matches to API reference.  But when we have a look at Zoom's API call logs, last_name field was somehow rewritten(I've set "Lastname" to _cf7zwr-last_name_ and "Firstname" to _cf7zwr-first_name_ as a test).
![Zoom_required_field](https://user-images.githubusercontent.com/39087732/89507137-106a6400-d807-11ea-8c53-cd43f54008a3.png)
![wp](https://user-images.githubusercontent.com/39087732/89507141-119b9100-d807-11ea-9375-6c7675438390.png)
![API_result](https://user-images.githubusercontent.com/39087732/89507139-1102fa80-d807-11ea-95d4-f537cc5f5cd7.png)

**Comment by usame-algan** [comment]
Thanks @makiren!

I pushed a release that should fix this bug.
