### ISSUE TITLE
Feature request - Checkbox to confirm

### ISSUE THREAD

**Issue by briandorricott** [usame-algan/cf7-zoom-webinar-registration#3]
I've installed this plug-in and got it working inside 5 minutes. Great implementation.

The only addition I'd like to see is the option to require users to check a box to be added to the seminar. Then the form can be used to give someone options
[  ] Join my webinar
[  ] Join my mailing list
[  ] Send me brochure about XXX
and they can select any of the options.

Would it be possible to add this?

Brian

**Comment by briandorricott** [comment]
One way to do this would be to add a form variable:
    cf7zwr-<zoom-webinar-id>
Then if the form variable exists, send the request.

So if someone doesn't want to use the checkbox, the can put the webinar id in a hidden field.
If they want to give the option, they can use the form checkbox.

Just thinking about it, this would allow people to offer more than one webinar each on a different date/time using different id.

Thinking about it, would no longer need the "Zoom" tab in the CF7 configuration.

**Comment by usame-algan** [comment]
@briandorricott I like the suggestion of sending the registration conditionally. The current implementation only supports a 1-to-1 mapping but I can also see the use case of having one form to register to multiple webinars.

I will try to include this feature in the next release. Of course you're also welcome to open a PR
